# Generated by Django 4.1.7 on 2023-02-22 03:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.functions.text


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ShoppingItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128, unique=True)),
                (
                    "photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="shoppingitem_photos"
                    ),
                ),
            ],
            options={
                "ordering": [django.db.models.functions.text.Lower("name")],
            },
        ),
        migrations.CreateModel(
            name="UserShoppingItems",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveSmallIntegerField()),
                ("checked", models.BooleanField(default=False)),
                (
                    "shoppingitem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="shoppingitems.shoppingitem",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.AddField(
            model_name="shoppingitem",
            name="users",
            field=models.ManyToManyField(
                related_name="shoppingitems",
                through="shoppingitems.UserShoppingItems",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
